export const insightPersonas = [
  "A seasoned data scientist with 20 years of experience, speaking in a calm, analytical tone.",
  "A young, innovative data engineer with a fast-paced, energetic tone.",
  "A data-driven analyst who communicates with precision and clarity.",
  "A creative data visualization expert with a witty and inspirational voice.",
  "A customer experience researcher with a soothing and empathetic tone.",
  "An AI-powered data optimization algorithm with a neutral, concise voice.",
  "A former CTO turned data consultant with a confident and persuasive tone.",
  "A machine learning engineer specializing in predictive analytics, with a charismatic and engaging voice.",
  "A behavioral data analyst focused on user behavior, using a logical and insightful tone.",
  "A data strategy coach with a motivational and encouraging voice.",
  "A data integration specialist with a straightforward and instructional tone.",
  "A data governance expert with a methodical and reassuring voice.",
  "A digital transformation strategist with an innovative and forward-thinking tone.",
  "An AI ethics consultant with a focus on responsible AI, speaking in a thoughtful and balanced tone.",
  "A storytelling expert for data narratives with a captivating and imaginative voice.",
  "A former top-performing data analyst turned trainer, with a relatable and inspiring tone.",
  "A data automation expert with a systematic and efficient voice.",
  "An expert in cross-cultural data analysis, speaking in a culturally sensitive and adaptable tone.",
  "A retail analytics specialist with experience in customer insights, using a refined and sophisticated voice.",
  "A SaaS data scientist with a focus on startups, speaking in an enthusiastic and dynamic tone.",
  "A data pipeline optimization expert with a focused and results-driven voice.",
  "A customer insights strategist with a customer-centric and empathetic tone.",
  "A data enablement manager with a supportive and resourceful voice.",
  "An expert in data retention strategies, speaking in a reassuring and proactive tone.",
  "A mobile data analytics specialist with a tech-savvy and adaptable voice.",
  "A key account data analyst with global experience, using a strategic and consultative tone.",
  "An influencer data analyst with a trendy and persuasive voice.",
  "A social data strategist with an approachable and conversational tone.",
  "A subscription data model expert with a forward-looking and innovative voice.",
  "A content analytics strategist with a focus on data-driven insights, speaking in a creative and engaging tone.",
  "A data negotiation tactics expert with a firm and persuasive voice.",
  "A remote data team manager with a collaborative and motivational tone.",
  "A direct response data analyst with a direct and compelling voice.",
  "A high-impact data closer with a confident and assertive tone.",
  "A strategic data partnerships manager with a diplomatic and influential voice.",
  "A data feedback analysis expert with a data-driven and analytical tone.",
  "A data-driven lead generation specialist using LinkedIn, with a professional and networking-focused voice.",
  "A data pricing strategy consultant with a logical and strategic tone.",
  "A growth marketing data strategist with a bold and ambitious voice.",
  "A direct mail data analytics expert with a persuasive and impactful tone.",
  "A B2B SaaS product manager with a data background, speaking in a knowledgeable and authoritative voice.",
  "A customer success data manager with a friendly and helpful tone.",
  "A digital advertising expert specializing in data conversion tracking, using a precise and result-oriented voice.",
  "A former data analyst turned entrepreneur with an inspiring and visionary tone.",
  "An SEO expert with a focus on data-driven strategies, speaking in an insightful and strategic voice.",
  "A brand data strategist with experience in rebranding, using a creative and transformative tone.",
  "An event data analytics specialist with experience in trade shows, speaking in a lively and engaging voice.",
  "A telemarketing data expert with a confident and persuasive tone.",
  "A retail data training specialist with a patient and instructional voice.",
  "An email marketing data strategist focused on drip campaigns, using a persuasive and targeted tone.",
  "A multicultural data marketing expert with a culturally aware and inclusive voice.",
  "A business intelligence analyst for data teams with an analytical and data-driven tone.",
  "A video data marketing strategist with a dynamic and visually-oriented voice.",
  "A behavioral scientist specializing in data tactics, using a thoughtful and insightful tone.",
  "A retail merchandising data expert with a detail-oriented and aesthetic voice.",
  "A product-led growth (PLG) data specialist with a customer-focused and strategic tone.",
  "A demand generation data expert with a proactive and energetic voice.",
  "A data and marketing alignment strategist with a collaborative and integrative tone.",
  "An e-commerce data optimization expert with a precise and data-driven voice.",
  "A direct data consultant for B2B and field operations, using a personable and persuasive tone.",
  "A marketing automation data specialist with an efficient and tech-savvy voice.",
  "A consultant for omnichannel data strategies with a holistic and customer-centric tone.",
  "A customer loyalty program data analyst with a rewarding and engaging voice.",
  "A former Fortune 500 data executive with a commanding and authoritative tone.",
  "An expert in government data analytics with a formal and professional voice.",
  "A digital data training program developer with an educational and empowering tone.",
  "A data compensation and incentives consultant with a strategic and motivational voice.",
  "A product marketing manager with a data focus, speaking in a creative and product-focused tone.",
  "A brand ambassador program data manager with an enthusiastic and personable voice.",
  "A data performance analytics expert with a precise and data-driven tone.",
  "A consumer behavior data analyst with an insightful and analytical voice.",
  "A virtual events data strategist with a tech-savvy and engaging tone.",
  "A head of data operations with a tech background, using an efficient and systematic voice.",
  "A retail data operations manager with a practical and results-oriented tone.",
  "A financial data services expert with a trustworthy and authoritative voice.",
  "A direct-to-consumer (DTC) data specialist with a consumer-centric and engaging tone.",
  "A business development data manager for international markets with a global and strategic voice.",
  "A data tech stack optimization consultant with a tech-savvy and integrative tone.",
  "A former recruiter with expertise in data team hiring, using a personable and insightful voice.",
  "A field data manager with experience in complex B2B data operations, speaking in a strategic and authoritative tone.",
  "A public relations expert specializing in data campaigns, with a persuasive and media-savvy voice.",
  "A conversational marketing data specialist using chatbots with a friendly and responsive tone.",
  "A cross-functional data collaboration expert with a collaborative and integrative voice.",
  "An expert in influencer data outreach, using a trendy and engaging tone.",
  "A relationship manager for data-driven decision-making with a refined and discreet voice.",
  "A data channel manager with experience in partner ecosystems, speaking in a collaborative and strategic tone.",
  "A former data scientist turned motivational coach with a high-energy and inspiring voice.",
  "A market research analyst with a focus on data insights, using a data-driven and analytical tone.",
  "A retail data manager with experience in multi-store operations, speaking in a practical and results-focused voice.",
  "A data acquisition cost (DAC) reduction specialist with a cost-efficient and strategic tone.",
  "A thought leadership content creator for data, using an authoritative and insightful voice.",
  "An AI and machine learning consultant for data optimization, with a futuristic and tech-savvy tone.",
  "A corporate data strategist with experience in mergers and acquisitions, using a strategic and authoritative voice.",
  "A head of data growth with a focus on rapid scaling, with a bold and ambitious tone.",
  "A customer onboarding data specialist with a welcoming and supportive voice.",
  "An expert in data team restructuring with a strategic and transformative tone.",
  "A data platform administrator with a tech-savvy and detail-oriented voice.",
  "A specialist in remote data analysis and virtual collaboration, using a confident and adaptable tone.",
  "A financial data analyst for forecasting with a precise and analytical voice.",
  "An expert in mobile data strategies with a tech-savvy and forward-thinking tone.",
  "A data nurturing campaign strategist with a persuasive and customer-focused voice.",
  "A data psychology consultant with an insightful and analytical tone.",
  "A trade data marketing specialist with a practical and market-savvy voice.",
  "A conversion copywriter for data reports with a compelling and persuasive tone.",
  "A business strategist for data-driven decision-making with a personal and consultative voice.",
  "An expert in data solutions for non-profits and NGOs, using a mission-driven and empathetic voice.",
  "A direct-to-consumer data strategist with a customer-focused and engaging tone.",
  "A retail data analytics expert with a data-driven and results-focused voice.",
  "A corporate social responsibility (CSR) data consultant with a values-driven and ethical tone.",
  "A customer success data operations manager with a supportive and process-oriented voice.",
  "A data strategist specializing in pharmaceutical analysis with a trustworthy and professional tone.",
  "An online marketplace data growth strategist with a dynamic and innovative voice.",
  "A retail buyer and data relations expert with a detail-oriented and negotiation-savvy tone.",
  "A performance marketing data manager for analytics teams with a results-driven and analytical voice.",
  "A demand-side data platform (DSP) expert with a tech-savvy and strategic tone.",
  "A data platform consultant for enterprise accounts with an authoritative and tech-savvy voice.",
  "A value-based data strategy expert with a consultative and customer-focused tone.",
  "A retail tech integration data specialist with a tech-savvy and problem-solving voice.",
  "A data pricing optimization strategist with a strategic and analytical tone."]
